//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GosAutoInspection.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drivers
    {
        public int GUID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string ThirdName { get; set; }
        public string PassNum { get; set; }
        public string RegAdress { get; set; }
        public string LifeAdress { get; set; }
        public string Company { get; set; }
        public string JobName { get; set; }
        public string PhoneNum { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }

        public string ImagePath
        {
            get
            {
                return "../../Resources/photo/" + this.Photo;
            }
        }
    }
}
